### ISSUE TITLE
Actualización de Datos

### ISSUE THREAD

**Issue by WashingtonFigueroa** [deividscriollo/nethbook#36]
Clava bajar a 6 caracteres >> Barra adicional nivel de seguridad con los 3 colores
Texto mas Claro, letras mas grandes

**Comment by deividscriollo** [comment]
cuando sale texto Ingrese Ingrese una contraseña es requerido o cualquier otro texto de error debe estar el texto mas arriba o mas pegado a la linea del input esta muy abajo y a la vez el texto esta muy grande bajar 1 o 2 px

**Comment by JuanKlopez** [comment]
no esta subida a la rama desarrollo
